---
language: ruby
before_script:
  - ./install.sh
  - puppet module generate user-module --skip-interview
sudo: false
env:
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
script: ./test.sh
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.0"
